/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package minesweeper;

import java.util.Scanner;

public class MinesweeperApp {


    public static void main(String[] args) {
        GameLogic game = new GameLogic();
        
        Scanner scanner = new Scanner(System.in);
        System.out.println("Enter width of grid: ");
        int width = scanner.nextInt();
        
        System.out.println("Enter height of grid: ");
        int height = scanner.nextInt();
        
        System.out.println("Enter amount of bombs of grid: ");
        int bombs = scanner.nextInt();
        
        game.startGame(width, height, bombs);
        

        while (!game.isGameOver()) {
            game.renderWorld();
            
            int[] cords = GameLogic.getUserInput();
            game.clickCell(cords[0], cords[1]);
        }
        System.out.println("Game Over");
        game.renderWorld();
    }
}
